### ISSUE TITLE
Cleanup needed for the Contribute index page

### ISSUE THREAD

**Issue by orcmid** [MicrosoftDocs/Contribute#797]
This covers pull request #796 already submitted along with additional changes for complete cleanup.

PS: I didn't realize there is an automatic setting of assignees for issues here.  (Regretting Discussion is not enabled on these projects and I can't create issues over on the fork for managing myself :(

PPS: Taking advantage of a new GitHub feature for tasks.

PPPS: Issues #801 and #802 indicate there are more speed-bumps

```[tasklist]
### Tasks
- [x] Update the Contribute page to reflect the changes in GitHub's Process and the related dialogs
- [x] Smooth speed bumps over what has happened and what the reader is seeing at the moment.
- [x] Replace the images along with the improved narrative
- [x] Determine where and how the pull request is actually submitted and amend the description accordingly
- [x] Improve guard rails for someone attempting the procedure who is not adept with both GitHub and the markdown additions used as part of OPS.
```

**Comment by carlyrevier** [comment]
@orcmid - Thank you for this thorough analysis. I think I've addressed your tasks and the issues you opened, but please do let me know if you see more improvements in the new text. Appreciate your thoughtfulness! Thanks for being a contributor. :)
