### ISSUE TITLE
There is a responsiveness defect in presentation of Contribute/index.html

### ISSUE THREAD

**Issue by orcmid** [MicrosoftDocs/Contribute#803]
![F23xy080-2023-07-30-1605-BestReflowOfText](https://github.com/MicrosoftDocs/Contribute/assets/3372580/b5a86c7c-8c58-4031-ab83-f97b0159db41)

When the page is viewed at that browser-window width, in this portion of the Qucik-Edit explanation all text reflow has happened and the images are as shown.  The frame drawn around each of the two images is 640 pixels wide.  

If, in an effort to have the images be larger, widening the browser window has a contrary effect.  A wide empty side-area snaps into view and the previous material is in a narrowed column.  There is no improvement in rendering of the two images.

![F23xy081-2023-07-30-1608-AShrunkColumn](https://github.com/MicrosoftDocs/Contribute/assets/3372580/ce18a807-f26f-481d-bf69-41eaade72920)

## Investigations

1. The edit-icon.png (the one shown with the `Fork this  project ...` Tooltip is 898 x 230 pixels, so it is reduced somewhat.  The two commit-related PNG files are 1200 pixels wide and compressed to be almost unreadable.  The edit-article.png is only 468 pixels wide and is enlarged nicely.
2. Pages elsewhere in Learn documentation often have a right sidebar that emerges when the page is widened.  That is not happening here.  I did not search very far for pages with other PNGs for images.

This is a side-issue encountered while investigating for issue #797 
```[tasklist]
### Tasks
- [ ] See if providing clean 640px-wide images improves things
- [ ] Reconcile this with the 1200px "standard" here
- [ ] Consider annotating the screen captures with overlays that direct the viewer to the key part while providing valuable context
```

**Comment by orcmid** [comment]
I downloaded the PDF of the contributor guide and experience a similar problem to that of the first image.  The reflow is slightly different but the layout is comparable to the first image.  The **Propose Changes** and **Comparing Changes** images are borderline illegible.

**Comment by carlyrevier** [comment]
@orcmid - Thank you for investigating this issue. I've updated the images so they're larger on the page and representative of the UI changes since the page was last updated. Unfortunately, I can't do anything about the responsive design element of the platform.
